const provinces = [
  "آذربایجان شرقی",
  "آذربایجان غربی",
  "اردبیل",
  "اصفهان",
  "البرز",
  "ایلام",
  "بوشهر",
  "تهران",
  "چهارمحال و بختیاری",
  "خراسان جنوبی",
  "خراسان رضوی",
  "خراسان شمالی",
  "خوزستان",
  "زنجان",
  "سمنان",
  "سیستان و بلوچستان",
  "فارس",
  "قزوین",
  "قم",
  "کردستان",
  "کرمان",
  "کرمانشاه",
  "کهگیلویه و بویراحمد",
  "گلستان",
  "گیلان",
  "لرستان",
  "مازندران",
  "مرکزی",
  "هرمزگان",
  "همدان",
  "یزد",
];

const users = [
  { fullName: "مدیر سامانه هُما", phone: "09120000001", role: "ADMIN", email: "admin@homa.local" },
  { fullName: "مدیر هتل تهران", phone: "09120000002", role: "MANAGER", email: "tehran@homa.local" },
  { fullName: "مدیر هتل کیش", phone: "09120000003", role: "MANAGER", email: "kish@homa.local" },
  { fullName: "مدیر هتل شیراز", phone: "09120000004", role: "MANAGER", email: "shiraz@homa.local" },
  { fullName: "مدیر هتل اصفهان", phone: "09120000005", role: "MANAGER", email: "isfahan@homa.local" },
  { fullName: "مدیر هتل رشت", phone: "09120000006", role: "MANAGER", email: "rasht@homa.local" },
  { fullName: "مسافر نمونه هُما", phone: "09120000007", role: "GUEST", email: "guest@homa.local" },
];

const amenities = [
  { title: "اینترنت رایگان", description: "وای‌فای رایگان در اتاق‌ها و فضاهای عمومی" },
  { title: "استخر", description: "استخر سرپوشیده یا روباز مجموعه" },
  { title: "پارکینگ", description: "پارکینگ اختصاصی برای مهمانان" },
  { title: "صبحانه", description: "صبحانه روزانه همراه اقامت" },
  { title: "رستوران", description: "رستوران داخل مجموعه" },
  { title: "باشگاه ورزشی", description: "فضای ورزشی مجهز" },
  { title: "ترانسفر فرودگاهی", description: "خدمات رفت‌وبرگشت فرودگاهی" },
  { title: "پذیرش ۲۴ ساعته", description: "پاسخ‌گویی شبانه‌روزی پذیرش" },
];

const hotels = [
  {
    name: "هتل اسپیناس پالاس",
    slug: "espinas-palace",
    province: "تهران",
    managerPhone: "09120000002",
    address: "تهران، سعادت‌آباد، میدان بهرود",
    postalCode: "1997614311",
    stars: "5",
    metroAccess: "NO",
    description: "هتلی لوکس با چشم‌انداز شهر تهران و خدمات کامل اقامتی.",
    geometry: { type: "Point", coordinates: [51.3639, 35.7917] },
    amenities: ["اینترنت رایگان", "استخر", "پارکینگ", "صبحانه", "رستوران", "باشگاه ورزشی", "پذیرش ۲۴ ساعته"],
    rooms: [
      { name: "اتاق استاندارد اسپیناس", slug: "espinas-standard", capacity: 2, price: 6900000 },
      { name: "اتاق دبل اسپیناس", slug: "espinas-double", capacity: 2, price: 8300000 },
      { name: "سوئیت رویال اسپیناس", slug: "espinas-royal-suite", capacity: 4, price: 14800000 },
    ],
  },
  {
    name: "هتل شایگان کیش",
    slug: "shaygan-kish",
    province: "هرمزگان",
    managerPhone: "09120000003",
    address: "کیش، میدان پردیس، بلوار رودکی",
    postalCode: "7941899911",
    stars: "5",
    metroAccess: "NO",
    description: "اقامتی آرام در نزدیکی مراکز خرید و ساحل جزیره کیش.",
    geometry: { type: "Point", coordinates: [53.9994, 26.5329] },
    amenities: ["اینترنت رایگان", "استخر", "صبحانه", "رستوران", "ترانسفر فرودگاهی", "پذیرش ۲۴ ساعته"],
    rooms: [
      { name: "اتاق دوتخته شایگان", slug: "shaygan-double", capacity: 2, price: 5400000 },
      { name: "اتاق سه‌تخته شایگان", slug: "shaygan-triple", capacity: 3, price: 6800000 },
      { name: "سوئیت ساحلی شایگان", slug: "shaygan-sea-suite", capacity: 4, price: 9900000 },
    ],
  },
  {
    name: "هتل زندیه شیراز",
    slug: "zandiyeh-shiraz",
    province: "فارس",
    managerPhone: "09120000004",
    address: "شیراز، خیابان هجرت، پشت ارگ کریم‌خان",
    postalCode: "7136911111",
    stars: "5",
    metroAccess: "YES",
    description: "ترکیبی از معماری ایرانی و امکانات مدرن در قلب شیراز.",
    geometry: { type: "Point", coordinates: [52.5428, 29.6184] },
    amenities: ["اینترنت رایگان", "استخر", "پارکینگ", "صبحانه", "رستوران", "پذیرش ۲۴ ساعته"],
    rooms: [
      { name: "اتاق سنتی زندیه", slug: "zandiyeh-traditional", capacity: 2, price: 4600000 },
      { name: "اتاق دبل زندیه", slug: "zandiyeh-double", capacity: 2, price: 5200000 },
      { name: "سوئیت زندیه", slug: "zandiyeh-suite", capacity: 4, price: 8700000 },
    ],
  },
  {
    name: "هتل عباسی اصفهان",
    slug: "abbasi-isfahan",
    province: "اصفهان",
    managerPhone: "09120000005",
    address: "اصفهان، چهارباغ عباسی، خیابان آمادگاه",
    postalCode: "8146641111",
    stars: "5",
    metroAccess: "YES",
    description: "هتل تاریخی اصفهان با حیاط ایرانی و دسترسی مناسب به دیدنی‌های شهر.",
    geometry: { type: "Point", coordinates: [51.6679, 32.6516] },
    amenities: ["اینترنت رایگان", "پارکینگ", "صبحانه", "رستوران", "باشگاه ورزشی", "پذیرش ۲۴ ساعته"],
    rooms: [
      { name: "اتاق چشم‌انداز عباسی", slug: "abbasi-view", capacity: 2, price: 5800000 },
      { name: "اتاق پردیس عباسی", slug: "abbasi-paradise", capacity: 3, price: 7100000 },
      { name: "سوئیت قاجار عباسی", slug: "abbasi-qajar-suite", capacity: 4, price: 11200000 },
    ],
  },
  {
    name: "هتل بزرگ کادوس",
    slug: "kadus-rasht",
    province: "گیلان",
    managerPhone: "09120000006",
    address: "رشت، بلوار آزادی، منظریه",
    postalCode: "4163911111",
    stars: "5",
    metroAccess: "NO",
    description: "اقامتی سبز و آرام در مرکز رشت با دسترسی آسان به جاذبه‌های گیلان.",
    geometry: { type: "Point", coordinates: [49.5832, 37.2808] },
    amenities: ["اینترنت رایگان", "استخر", "پارکینگ", "صبحانه", "رستوران", "پذیرش ۲۴ ساعته"],
    rooms: [
      { name: "اتاق دبل کادوس", slug: "kadus-double", capacity: 2, price: 3900000 },
      { name: "اتاق خانوادگی کادوس", slug: "kadus-family", capacity: 4, price: 6300000 },
      { name: "سوئیت سبز کادوس", slug: "kadus-green-suite", capacity: 5, price: 8200000 },
    ],
  },
];

module.exports = { provinces, users, amenities, hotels };
